/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IfspLife;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Hemaa
 */
public class Buy_Drug extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pre = null;
ResultSet res= null;
    public Buy_Drug() {
        initComponents();
        company();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        JLabel_Codigo_Remedio = new javax.swing.JLabel();
        JTextField_Codigo_Remedio = new javax.swing.JTextField();
        JLabel_Nome_Remedio = new javax.swing.JLabel();
        JTextField_Nome_Remedio = new javax.swing.JTextField();
        JLabel_Tipo_Remedio = new javax.swing.JLabel();
        JComboBox_Tipo_Remedio = new javax.swing.JComboBox<>();
        JLabel_Nome_Empresa = new javax.swing.JLabel();
        JComboBox_Nome_Empresa = new javax.swing.JComboBox<>();
        JLabel_Quantidade_Remedio = new javax.swing.JLabel();
        JComboBox_Quantidade_Remedio = new javax.swing.JComboBox<>();
        JLabel_PrecoCusto_Remedio = new javax.swing.JLabel();
        JTextField_PrecoCusto_Remedio = new javax.swing.JTextField();
        JLabel_Preco = new javax.swing.JLabel();
        JTextFieldPreco = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        JButton_Deletar = new javax.swing.JButton();
        JButton_Cancelar = new javax.swing.JButton();
        JButton_Comprar = new javax.swing.JButton();
        JButton_Atualizar = new javax.swing.JButton();
        JButton_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buy_Drug");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Adicionar Remédios ao Estoque");

        JLabel_Codigo_Remedio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_Codigo_Remedio.setText("Drug_Barcode : ");

        JTextField_Codigo_Remedio.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_RemedioKeyPressed(evt);
            }
        });

        JLabel_Nome_Remedio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_Nome_Remedio.setText("Drug_Name : ");

        JLabel_Tipo_Remedio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_Tipo_Remedio.setText("Drug_Type : ");

        JComboBox_Tipo_Remedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drug_Type : ", "Bills", "Injection", "Drink", "Fizzing" }));

        JLabel_Nome_Empresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_Nome_Empresa.setText("Company_Name : ");

        JComboBox_Nome_Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company_Name : " }));

        JLabel_Quantidade_Remedio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_Quantidade_Remedio.setText("Quantity : ");

        JComboBox_Quantidade_Remedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity : ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));

        JLabel_PrecoCusto_Remedio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_PrecoCusto_Remedio.setText("Cost_Price : ");

        JLabel_Preco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabel_Preco.setText("Amount : ");

        JButton_Deletar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Deletar.setText("Deletar");
        JButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_DeletarActionPerformed(evt);
            }
        });

        JButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Cancelar.setText("Cancelar");
        JButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CancelarActionPerformed(evt);
            }
        });

        JButton_Comprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Comprar.setText("Comprar");
        JButton_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ComprarActionPerformed(evt);
            }
        });

        JButton_Atualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Atualizar.setText("Atualizar");
        JButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AtualizarActionPerformed(evt);
            }
        });

        JButton_Limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Limpar.setText("Limpar");
        JButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabel_Codigo_Remedio)
                                    .addComponent(JLabel_Nome_Remedio)
                                    .addComponent(JLabel_Tipo_Remedio)
                                    .addComponent(JLabel_Nome_Empresa))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTextField_Nome_Remedio)
                                    .addComponent(JTextField_Codigo_Remedio)
                                    .addComponent(JComboBox_Tipo_Remedio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JComboBox_Nome_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabel_Quantidade_Remedio)
                                    .addComponent(JLabel_PrecoCusto_Remedio)
                                    .addComponent(JLabel_Preco))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTextField_PrecoCusto_Remedio)
                                    .addComponent(JComboBox_Quantidade_Remedio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JButton_Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButton_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JButton_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel_Codigo_Remedio)
                            .addComponent(JTextField_Codigo_Remedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel_Nome_Remedio)
                            .addComponent(JTextField_Nome_Remedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JLabel_Preco)
                                .addComponent(JTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JLabel_Tipo_Remedio)
                                .addComponent(JComboBox_Tipo_Remedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel_Nome_Empresa)
                            .addComponent(JComboBox_Nome_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel_Quantidade_Remedio)
                            .addComponent(JComboBox_Quantidade_Remedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel_PrecoCusto_Remedio)
                            .addComponent(JTextField_PrecoCusto_Remedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_Comprar)
                    .addComponent(JButton_Cancelar)
                    .addComponent(JButton_Atualizar)
                    .addComponent(JButton_Limpar)
                    .addComponent(JButton_Deletar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        setSize(new java.awt.Dimension(688, 317));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_LimparActionPerformed
        clear();
    }//GEN-LAST:event_JButton_LimparActionPerformed

    private void JButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_AtualizarActionPerformed

    }//GEN-LAST:event_JButton_AtualizarActionPerformed

    private void JButton_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ComprarActionPerformed

    }//GEN-LAST:event_JButton_ComprarActionPerformed

    private void JButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButton_CancelarActionPerformed

    private void JButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_DeletarActionPerformed

    }//GEN-LAST:event_JButton_DeletarActionPerformed

    private void JTextField_Codigo_RemedioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_RemedioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String sql = "select * from purchase where BARCODE='"+JTextField_Codigo_Remedio.getText()+"' " ;
            try{
                pre=con.prepareStatement(sql);
                res=pre.executeQuery();
                if(res.next()){
                    String Name = res.getString("NAME");
                    JTextField_Nome_Remedio.setText(Name);

                    String Type = res.getString("TYPE");
                    JComboBox_Tipo_Remedio.setSelectedItem(Type);

                    String C_name = res.getString("COMPANY_NAME");
                    JComboBox_Nome_Empresa.setSelectedItem(C_name);

                    String Price = res.getString("PRICE");
                    JTextField_PrecoCusto_Remedio.setText(Price);

                    String Quantity = res.getString("QUANTITY");
                    JComboBox_Quantidade_Remedio.setSelectedItem(Quantity);

                    String Amount = res.getString("AMOUNT");
                    JTextFieldPreco.setText(Amount);
                }else {
                    JOptionPane.showMessageDialog(null,"This Drug did not Exist before","Error",2);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
            }
        }
    }//GEN-LAST:event_JTextField_Codigo_RemedioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy_Drug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy_Drug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy_Drug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy_Drug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy_Drug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Atualizar;
    private javax.swing.JButton JButton_Cancelar;
    private javax.swing.JButton JButton_Comprar;
    private javax.swing.JButton JButton_Deletar;
    private javax.swing.JButton JButton_Limpar;
    private javax.swing.JComboBox<String> JComboBox_Nome_Empresa;
    private javax.swing.JComboBox<String> JComboBox_Quantidade_Remedio;
    private javax.swing.JComboBox<String> JComboBox_Tipo_Remedio;
    private javax.swing.JLabel JLabel_Codigo_Remedio;
    private javax.swing.JLabel JLabel_Nome_Empresa;
    private javax.swing.JLabel JLabel_Nome_Remedio;
    private javax.swing.JLabel JLabel_Preco;
    private javax.swing.JLabel JLabel_PrecoCusto_Remedio;
    private javax.swing.JLabel JLabel_Quantidade_Remedio;
    private javax.swing.JLabel JLabel_Tipo_Remedio;
    private javax.swing.JTextField JTextFieldPreco;
    private javax.swing.JTextField JTextField_Codigo_Remedio;
    private javax.swing.JTextField JTextField_Nome_Remedio;
    private javax.swing.JTextField JTextField_PrecoCusto_Remedio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private boolean check(){
        boolean found = false;
        //check if the barcode of drug is already inserted before
        String sql = "select BARCODE from purchase where BARCODE='"+JTextField_Codigo_Remedio.getText()+"' ";
        try{
        pre=con.prepareStatement(sql);
        res=pre.executeQuery();
        if(res.next()){
            found=true;
        }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",2);
        }
    return found;
    }
    private void company(){
        String sql = "select NAME from company";
        try{
            pre=con.prepareStatement(sql);
            res=pre.executeQuery();
            while(res.next()){
                JComboBox_Nome_Empresa.addItem(res.getString("NAME"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
        }
    }
    private void clear(){
        JTextField_Codigo_Remedio.setText("");
        JTextField_PrecoCusto_Remedio.setText("");
        JTextFieldPreco.setText("");
        JTextField_Nome_Remedio.setText("");
        JComboBox_Quantidade_Remedio.setSelectedIndex(0);
        JComboBox_Nome_Empresa.setSelectedIndex(0);
        JComboBox_Tipo_Remedio.setSelectedIndex(0);
    }
}