/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IfspLife;

/**
 *
 * @author xandy
 */
public class ComprarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProdutos
     */
    public ComprarProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundImage = new javax.swing.JPanel();
        logoIFSP_LIFE = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        JLabel_Codigo_Remedio = new javax.swing.JLabel();
        JTextField_Codigo_Remedio = new javax.swing.JTextField();
        JLabel_Nome_Remedio = new javax.swing.JLabel();
        JTextField_Nome_Remedio = new javax.swing.JTextField();
        JLabel_Tipo_Remedio = new javax.swing.JLabel();
        JComboBox_Tipo_Remedio = new javax.swing.JComboBox<>();
        JLabel_Nome_Empresa = new javax.swing.JLabel();
        JComboBox_Nome_Empresa = new javax.swing.JComboBox<>();
        JLabel_Quantidade_Remedio = new javax.swing.JLabel();
        JComboBox_Quantidade_Remedio = new javax.swing.JComboBox<>();
        JLabel_PrecoCusto_Remedio = new javax.swing.JLabel();
        JTextField_PrecoCusto_Remedio = new javax.swing.JTextField();
        JLabel_Preco = new javax.swing.JLabel();
        JTextFieldPreco = new javax.swing.JTextField();
        JButton_Deletar = new javax.swing.JButton();
        JButton_Atualizar = new javax.swing.JButton();
        JButton_Comprar = new javax.swing.JButton();
        JButton_Limpar = new javax.swing.JButton();
        JButton_Cancelar = new javax.swing.JButton();
        JSeparador = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        pro_day = new javax.swing.JComboBox<>();
        pro_month = new javax.swing.JComboBox<>();
        pro_year = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        exp_day = new javax.swing.JComboBox<>();
        exp_month = new javax.swing.JComboBox<>();
        exp_year = new javax.swing.JComboBox<>();
        BackGroundImageGradient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGroundImage.setMaximumSize(new java.awt.Dimension(800, 500));
        BackGroundImage.setMinimumSize(new java.awt.Dimension(800, 500));
        BackGroundImage.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoIFSP_LIFE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIFSP_LIFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/default_transparent_765x625_resized.png"))); // NOI18N
        BackGroundImage.add(logoIFSP_LIFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 140));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Adicionar Produtos ao Estoque");
        BackGroundImage.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 910, 60));

        JLabel_Codigo_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Codigo_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio.setText("Código do Produto:");
        BackGroundImage.add(JLabel_Codigo_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, -1));

        JTextField_Codigo_Remedio.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_RemedioActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_RemedioKeyPressed(evt);
            }
        });
        BackGroundImage.add(JTextField_Codigo_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 156, -1));

        JLabel_Nome_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Nome_Remedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Nome_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Nome_Remedio.setText("Nome do Remédio:");
        BackGroundImage.add(JLabel_Nome_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 200, 210, -1));
        BackGroundImage.add(JTextField_Nome_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 156, -1));

        JLabel_Tipo_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Tipo_Remedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Tipo_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Tipo_Remedio.setText("Tipo do Remédio:");
        BackGroundImage.add(JLabel_Tipo_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, -1));

        JComboBox_Tipo_Remedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drug_Type : ", "Bills", "Injection", "Drink", "Fizzing" }));
        JComboBox_Tipo_Remedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox_Tipo_RemedioActionPerformed(evt);
            }
        });
        BackGroundImage.add(JComboBox_Tipo_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 156, -1));

        JLabel_Nome_Empresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Nome_Empresa.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Nome_Empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Nome_Empresa.setText("Nome da Empresa:");
        BackGroundImage.add(JLabel_Nome_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, -1));

        JComboBox_Nome_Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company_Name : " }));
        BackGroundImage.add(JComboBox_Nome_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 156, -1));

        JLabel_Quantidade_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Quantidade_Remedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Quantidade_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Quantidade_Remedio.setText("Quantidade:");
        BackGroundImage.add(JLabel_Quantidade_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, -1));

        JComboBox_Quantidade_Remedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity : ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        BackGroundImage.add(JComboBox_Quantidade_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 156, -1));

        JLabel_PrecoCusto_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_PrecoCusto_Remedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_PrecoCusto_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_PrecoCusto_Remedio.setText("Preco de Custo:");
        BackGroundImage.add(JLabel_PrecoCusto_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 240, 200, -1));

        JTextField_PrecoCusto_Remedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_PrecoCusto_RemedioActionPerformed(evt);
            }
        });
        BackGroundImage.add(JTextField_PrecoCusto_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 156, -1));

        JLabel_Preco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Preco.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Preco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Preco.setText("Preco de Venda:");
        BackGroundImage.add(JLabel_Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 280, 200, -1));
        BackGroundImage.add(JTextFieldPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 156, -1));

        JButton_Deletar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Deletar.setText("Deletar");
        JButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_DeletarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 111, -1));

        JButton_Atualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Atualizar.setText("Atualizar");
        JButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AtualizarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 115, -1));

        JButton_Comprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Comprar.setText("Comprar");
        JButton_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ComprarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 115, -1));

        JButton_Limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Limpar.setText("Limpar");
        JButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_LimparActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 94, -1));

        JButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Cancelar.setText("Cancelar");
        JButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CancelarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 94, -1));
        BackGroundImage.add(JSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 880, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data de Produção:");
        BackGroundImage.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 200, -1));

        pro_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day : ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        BackGroundImage.add(pro_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        pro_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month : ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BackGroundImage.add(pro_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        pro_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year : ", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        BackGroundImage.add(pro_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Data de Vencimento:");
        BackGroundImage.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 200, -1));

        exp_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day : ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        BackGroundImage.add(exp_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        exp_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month : ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BackGroundImage.add(exp_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        exp_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year : ", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        BackGroundImage.add(exp_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

        BackGroundImageGradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/gradient.png"))); // NOI18N
        BackGroundImageGradient.setText("jLabel1");
        BackGroundImage.add(BackGroundImageGradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextField_Codigo_RemedioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_RemedioKeyPressed

    }//GEN-LAST:event_JTextField_Codigo_RemedioKeyPressed

    private void JComboBox_Tipo_RemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox_Tipo_RemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox_Tipo_RemedioActionPerformed

    private void JButton_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ComprarActionPerformed

    }//GEN-LAST:event_JButton_ComprarActionPerformed

    private void JButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_AtualizarActionPerformed

    }//GEN-LAST:event_JButton_AtualizarActionPerformed

    private void JButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_DeletarActionPerformed

    }//GEN-LAST:event_JButton_DeletarActionPerformed

    private void JButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_LimparActionPerformed
    }//GEN-LAST:event_JButton_LimparActionPerformed

    private void JButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButton_CancelarActionPerformed

    private void JTextField_Codigo_RemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_RemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_RemedioActionPerformed

    private void JTextField_PrecoCusto_RemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_PrecoCusto_RemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_PrecoCusto_RemedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundImage;
    private javax.swing.JLabel BackGroundImageGradient;
    public javax.swing.JButton JButton_Atualizar;
    private javax.swing.JButton JButton_Cancelar;
    public javax.swing.JButton JButton_Comprar;
    public javax.swing.JButton JButton_Deletar;
    private javax.swing.JButton JButton_Limpar;
    public javax.swing.JComboBox<String> JComboBox_Nome_Empresa;
    public javax.swing.JComboBox<String> JComboBox_Quantidade_Remedio;
    public javax.swing.JComboBox<String> JComboBox_Tipo_Remedio;
    private javax.swing.JLabel JLabel_Codigo_Remedio;
    private javax.swing.JLabel JLabel_Nome_Empresa;
    private javax.swing.JLabel JLabel_Nome_Remedio;
    private javax.swing.JLabel JLabel_Preco;
    private javax.swing.JLabel JLabel_PrecoCusto_Remedio;
    private javax.swing.JLabel JLabel_Quantidade_Remedio;
    private javax.swing.JLabel JLabel_Tipo_Remedio;
    private javax.swing.JSeparator JSeparador;
    private javax.swing.JTextField JTextFieldPreco;
    private javax.swing.JTextField JTextField_Codigo_Remedio;
    private javax.swing.JTextField JTextField_Nome_Remedio;
    private javax.swing.JTextField JTextField_PrecoCusto_Remedio;
    private javax.swing.JLabel Titulo;
    public javax.swing.JComboBox<String> exp_day;
    public javax.swing.JComboBox<String> exp_month;
    public javax.swing.JComboBox<String> exp_year;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel logoIFSP_LIFE;
    public javax.swing.JComboBox<String> pro_day;
    public javax.swing.JComboBox<String> pro_month;
    public javax.swing.JComboBox<String> pro_year;
    // End of variables declaration//GEN-END:variables
}
