/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IfspLife;

/**
 *
 * @author xandy
 */
public class Empresa extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProdutos
     */
    public Empresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundImage = new javax.swing.JPanel();
        logoIFSP_LIFE = new javax.swing.JLabel();
        JLabel_Titulo = new javax.swing.JLabel();
        JButton_Deletar = new javax.swing.JButton();
        JButton_Atualizar = new javax.swing.JButton();
        JButton_Comprar = new javax.swing.JButton();
        JButton_Limpar = new javax.swing.JButton();
        JButton_Cancelar = new javax.swing.JButton();
        JSeparador = new javax.swing.JSeparator();
        JLabel_Codigo_Remedio = new javax.swing.JLabel();
        JTextField_Codigo_Remedio2 = new javax.swing.JTextField();
        JLabel_Codigo_Remedio1 = new javax.swing.JLabel();
        JScrollPane_FornecedorEndereco = new javax.swing.JScrollPane();
        JTextArea_FornecedorEndereco = new javax.swing.JTextArea();
        JLabel_Codigo_Remedio2 = new javax.swing.JLabel();
        JTextField_Codigo_Remedio3 = new javax.swing.JTextField();
        JScrollPane_Fornecedores = new javax.swing.JScrollPane();
        JTable_Fornecedores = new javax.swing.JTable();
        BackGroundImageGradient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGroundImage.setMaximumSize(new java.awt.Dimension(800, 500));
        BackGroundImage.setMinimumSize(new java.awt.Dimension(800, 500));
        BackGroundImage.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoIFSP_LIFE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIFSP_LIFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/default_transparent_765x625_resized.png"))); // NOI18N
        BackGroundImage.add(logoIFSP_LIFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 140));

        JLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Titulo.setText("Contato - Fabricantes");
        BackGroundImage.add(JLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 920, 70));

        JButton_Deletar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Deletar.setText("Deletar");
        JButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_DeletarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 111, -1));

        JButton_Atualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Atualizar.setText("Atualizar");
        JButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AtualizarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 115, -1));

        JButton_Comprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Comprar.setText("Comprar");
        JButton_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ComprarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 115, -1));

        JButton_Limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Limpar.setText("Limpar");
        JButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_LimparActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 94, -1));

        JButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Cancelar.setText("Cancelar");
        JButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CancelarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 94, -1));
        BackGroundImage.add(JSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 880, 10));

        JLabel_Codigo_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Codigo_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio.setText("Endereco Fabricante: ");
        BackGroundImage.add(JLabel_Codigo_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, -1));

        JTextField_Codigo_Remedio2.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio2ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio2KeyPressed(evt);
            }
        });
        BackGroundImage.add(JTextField_Codigo_Remedio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 220, -1));

        JLabel_Codigo_Remedio1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio1.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Codigo_Remedio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio1.setText("Telefone da Empresa:");
        BackGroundImage.add(JLabel_Codigo_Remedio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, -1));

        JTextArea_FornecedorEndereco.setColumns(20);
        JTextArea_FornecedorEndereco.setRows(5);
        JScrollPane_FornecedorEndereco.setViewportView(JTextArea_FornecedorEndereco);

        BackGroundImage.add(JScrollPane_FornecedorEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 220, -1));

        JLabel_Codigo_Remedio2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio2.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Codigo_Remedio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio2.setText("Nome da Empresa:");
        BackGroundImage.add(JLabel_Codigo_Remedio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 230, -1));

        JTextField_Codigo_Remedio3.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio3ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio3KeyPressed(evt);
            }
        });
        BackGroundImage.add(JTextField_Codigo_Remedio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 220, -1));

        JTable_Fornecedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JTable_Fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "        Name", "        Address", "        Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JScrollPane_Fornecedores.setViewportView(JTable_Fornecedores);

        BackGroundImage.add(JScrollPane_Fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 390, 180));

        BackGroundImageGradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/gradient.png"))); // NOI18N
        BackGroundImageGradient.setText("jLabel1");
        BackGroundImage.add(BackGroundImageGradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ComprarActionPerformed

    }//GEN-LAST:event_JButton_ComprarActionPerformed

    private void JButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_AtualizarActionPerformed

    }//GEN-LAST:event_JButton_AtualizarActionPerformed

    private void JButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_DeletarActionPerformed

    }//GEN-LAST:event_JButton_DeletarActionPerformed

    private void JButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_LimparActionPerformed
    }//GEN-LAST:event_JButton_LimparActionPerformed

    private void JButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButton_CancelarActionPerformed

    private void JTextField_Codigo_Remedio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio2ActionPerformed

    private void JTextField_Codigo_Remedio2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio2KeyPressed

    }//GEN-LAST:event_JTextField_Codigo_Remedio2KeyPressed

    private void JTextField_Codigo_Remedio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio3ActionPerformed

    private void JTextField_Codigo_Remedio3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundImage;
    private javax.swing.JLabel BackGroundImageGradient;
    public javax.swing.JButton JButton_Atualizar;
    private javax.swing.JButton JButton_Cancelar;
    public javax.swing.JButton JButton_Comprar;
    public javax.swing.JButton JButton_Deletar;
    private javax.swing.JButton JButton_Limpar;
    private javax.swing.JLabel JLabel_Codigo_Remedio;
    private javax.swing.JLabel JLabel_Codigo_Remedio1;
    private javax.swing.JLabel JLabel_Codigo_Remedio2;
    private javax.swing.JLabel JLabel_Titulo;
    private javax.swing.JScrollPane JScrollPane_FornecedorEndereco;
    private javax.swing.JScrollPane JScrollPane_Fornecedores;
    private javax.swing.JSeparator JSeparador;
    private javax.swing.JTable JTable_Fornecedores;
    private javax.swing.JTextArea JTextArea_FornecedorEndereco;
    private javax.swing.JTextField JTextField_Codigo_Remedio2;
    private javax.swing.JTextField JTextField_Codigo_Remedio3;
    private javax.swing.JLabel logoIFSP_LIFE;
    // End of variables declaration//GEN-END:variables
}
