/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IfspLife;

import javax.swing.JOptionPane;

/**
 *
 * @author xandy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form TelaSplashScreen
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        IconX = new javax.swing.JLabel();
        LogoIFSP_LIFE = new javax.swing.JLabel();
        Login1 = new javax.swing.JLabel();
        Login2 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        BTNlogin = new javax.swing.JButton();
        BTNclear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGroundPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundPanel.setRequestFocusEnabled(false);
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/icons8-excluir-30.png"))); // NOI18N
        IconX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconXMouseClicked(evt);
            }
        });
        BackGroundPanel.add(IconX, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        LogoIFSP_LIFE.setBackground(new java.awt.Color(204, 0, 153));
        LogoIFSP_LIFE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoIFSP_LIFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/default_transparent_765x625.png"))); // NOI18N
        BackGroundPanel.add(LogoIFSP_LIFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 500));

        Login1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login1.setText("LOGIN");
        BackGroundPanel.add(Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 280, 70));

        Login2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login2.setText("LOGIN");
        BackGroundPanel.add(Login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 130, 40));
        BackGroundPanel.add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 220, 40));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setText("SENHA");
        BackGroundPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 60));
        BackGroundPanel.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 220, 40));

        BTNlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNlogin.setText("LOGIN");
        BackGroundPanel.add(BTNlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 120, 50));

        BTNclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNclear.setText("CLEAR");
        BackGroundPanel.add(BTNclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 120, 50));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BackGroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IconXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_IconXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Login login = new Login();
        login.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNclear;
    private javax.swing.JButton BTNlogin;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel IconX;
    private javax.swing.JLabel Login1;
    private javax.swing.JLabel Login2;
    private javax.swing.JLabel LogoIFSP_LIFE;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables
}
