/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IfspLife;

/**
 *
 * @author xandy
 */
public class NF extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProdutos
     */
    public NF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundImage = new javax.swing.JPanel();
        logoIFSP_LIFE = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        JSeparador = new javax.swing.JSeparator();
        JTextField_CodigoRemedio = new javax.swing.JTextField();
        JLabel_Quantidade = new javax.swing.JLabel();
        JLabel_CodigoRemedio = new javax.swing.JLabel();
        JComboBox_Quantidade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JLabel_ValorTotal = new javax.swing.JLabel();
        JLabel_Total = new javax.swing.JLabel();
        JButton_Gerar = new javax.swing.JButton();
        JButton_Cancelar = new javax.swing.JButton();
        BackGroundImageGradient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGroundImage.setMaximumSize(new java.awt.Dimension(800, 500));
        BackGroundImage.setMinimumSize(new java.awt.Dimension(800, 500));
        BackGroundImage.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoIFSP_LIFE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIFSP_LIFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/default_transparent_765x625_resized.png"))); // NOI18N
        BackGroundImage.add(logoIFSP_LIFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 140));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Emitir Nota");
        BackGroundImage.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 910, 60));
        BackGroundImage.add(JSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 900, 10));
        BackGroundImage.add(JTextField_CodigoRemedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 187, -1));

        JLabel_Quantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel_Quantidade.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Quantidade.setText("Quantidade");
        BackGroundImage.add(JLabel_Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 90, 20));

        JLabel_CodigoRemedio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel_CodigoRemedio.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_CodigoRemedio.setText("Codigo_Remedio");
        BackGroundImage.add(JLabel_CodigoRemedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, -1));

        JComboBox_Quantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity : ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        BackGroundImage.add(JComboBox_Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 150, 20));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Valor", "Vencimento", "Tipo", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BackGroundImage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 830, 140));

        JLabel_ValorTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JLabel_ValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_ValorTotal.setText("R$00.0");
        BackGroundImage.add(JLabel_ValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        JLabel_Total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLabel_Total.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Total.setText("Total : ");
        BackGroundImage.add(JLabel_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        JButton_Gerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Gerar.setText("Gerar");
        JButton_Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_GerarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Gerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 110, 50));

        JButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JButton_Cancelar.setText("Cancelar");
        JButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CancelarActionPerformed(evt);
            }
        });
        BackGroundImage.add(JButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 110, 50));

        BackGroundImageGradient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackGroundImageGradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/gradient.png"))); // NOI18N
        BackGroundImageGradient.setText("jLabel1");
        BackGroundImage.add(BackGroundImageGradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_GerarActionPerformed

    }//GEN-LAST:event_JButton_GerarActionPerformed

    private void JButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CancelarActionPerformed

    }//GEN-LAST:event_JButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundImage;
    private javax.swing.JLabel BackGroundImageGradient;
    private javax.swing.JButton JButton_Cancelar;
    private javax.swing.JButton JButton_Gerar;
    public javax.swing.JComboBox<String> JComboBox_Quantidade;
    private javax.swing.JLabel JLabel_CodigoRemedio;
    private javax.swing.JLabel JLabel_Quantidade;
    private javax.swing.JLabel JLabel_Total;
    private javax.swing.JLabel JLabel_ValorTotal;
    private javax.swing.JSeparator JSeparador;
    private javax.swing.JTextField JTextField_CodigoRemedio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoIFSP_LIFE;
    // End of variables declaration//GEN-END:variables
}
