/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IfspLife;

/**
 *
 * @author xandy
 */
public class UsuariosAtt extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public UsuariosAtt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IconX4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        logoIFSP_LIFE = new javax.swing.JLabel();
        JLabel_Titulo = new javax.swing.JLabel();
        JSeparador = new javax.swing.JSeparator();
        JLabel_Codigo_Remedio2 = new javax.swing.JLabel();
        JTextField_Codigo_Remedio3 = new javax.swing.JTextField();
        JLabel_Codigo_Remedio3 = new javax.swing.JLabel();
        JTextField_Codigo_Remedio4 = new javax.swing.JTextField();
        JLabel_Codigo_Remedio4 = new javax.swing.JLabel();
        JTextField_Codigo_Remedio5 = new javax.swing.JTextField();
        JLabel_Codigo_Remedio5 = new javax.swing.JLabel();
        JTextField_Codigo_Remedio6 = new javax.swing.JTextField();
        JLabel_Codigo_Remedio6 = new javax.swing.JLabel();
        JTextField_Codigo_Remedio7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pro_day = new javax.swing.JComboBox<>();
        pro_month = new javax.swing.JComboBox<>();
        pro_year = new javax.swing.JComboBox<>();
        JScrollPane_FornecedorEndereco = new javax.swing.JScrollPane();
        JTextArea_FornecedorEndereco = new javax.swing.JTextArea();
        JLabel_Codigo_Remedio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        users = new javax.swing.JTable();
        JLabel_Codigo_Remedio7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        updateuser = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        deleteuser = new javax.swing.JButton();
        adduser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1210, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 20, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pharmacy Managment System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/male_user_50px.png"))); // NOI18N
        jLabel3.setText("Welcome Admin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 70));

        IconX4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconX4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/icons8-excluir-30.png"))); // NOI18N
        IconX4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconX4MouseClicked(evt);
            }
        });
        jPanel1.add(IconX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 50, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        logoIFSP_LIFE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIFSP_LIFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/default_transparent_765x625_resized.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoIFSP_LIFE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoIFSP_LIFE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 600));

        JLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Titulo.setText("Usuarios");
        getContentPane().add(JLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 900, 60));
        getContentPane().add(JSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 1030, 10));

        JLabel_Codigo_Remedio2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio2.setText("Id do Usuario:");
        getContentPane().add(JLabel_Codigo_Remedio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, -1));

        JTextField_Codigo_Remedio3.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio3ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio3KeyPressed(evt);
            }
        });
        getContentPane().add(JTextField_Codigo_Remedio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 240, -1));

        JLabel_Codigo_Remedio3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio3.setText("Nome do Usuario:");
        getContentPane().add(JLabel_Codigo_Remedio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 230, -1));

        JTextField_Codigo_Remedio4.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio4ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio4KeyPressed(evt);
            }
        });
        getContentPane().add(JTextField_Codigo_Remedio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 240, -1));

        JLabel_Codigo_Remedio4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio4.setText("Contato do Usuario:");
        getContentPane().add(JLabel_Codigo_Remedio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 230, -1));

        JTextField_Codigo_Remedio5.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio5ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio5KeyPressed(evt);
            }
        });
        getContentPane().add(JTextField_Codigo_Remedio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 240, -1));

        JLabel_Codigo_Remedio5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio5.setText("Salário do Usuario:");
        getContentPane().add(JLabel_Codigo_Remedio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 230, -1));

        JTextField_Codigo_Remedio6.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio6ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio6KeyPressed(evt);
            }
        });
        getContentPane().add(JTextField_Codigo_Remedio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 240, -1));

        JLabel_Codigo_Remedio6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio6.setText("Nivel de Acesso:");
        getContentPane().add(JLabel_Codigo_Remedio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 230, 20));

        JTextField_Codigo_Remedio7.setToolTipText("Enter Barcode and Press Enter for Updating");
        JTextField_Codigo_Remedio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_Codigo_Remedio7ActionPerformed(evt);
            }
        });
        JTextField_Codigo_Remedio7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextField_Codigo_Remedio7KeyPressed(evt);
            }
        });
        getContentPane().add(JTextField_Codigo_Remedio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 240, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data de Nascimento:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, -1));

        pro_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day : ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(pro_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        pro_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month : ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(pro_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        pro_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year : ", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        getContentPane().add(pro_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        JTextArea_FornecedorEndereco.setColumns(20);
        JTextArea_FornecedorEndereco.setRows(5);
        JScrollPane_FornecedorEndereco.setViewportView(JTextArea_FornecedorEndereco);

        getContentPane().add(JScrollPane_FornecedorEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 250, -1));

        JLabel_Codigo_Remedio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio.setText("Endereco do Usuario:");
        getContentPane().add(JLabel_Codigo_Remedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 230, -1));

        users.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "DMA", "Telefone", "Salario", "Senha", "NivelAcesso", "Endereco"
            }
        ));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(users);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 450, 390));

        JLabel_Codigo_Remedio7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLabel_Codigo_Remedio7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Codigo_Remedio7.setText("Senha do Usuario:");
        getContentPane().add(JLabel_Codigo_Remedio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 230, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 240, -1));

        updateuser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateuser.setText("Update User");
        updateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuserActionPerformed(evt);
            }
        });
        getContentPane().add(updateuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 90, -1));

        deleteuser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteuser.setText("Delete User");
        deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserActionPerformed(evt);
            }
        });
        getContentPane().add(deleteuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        adduser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adduser.setText("Add User");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });
        getContentPane().add(adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 89, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconX4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconX4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_IconX4MouseClicked

    private void JTextField_Codigo_Remedio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio3ActionPerformed

    private void JTextField_Codigo_Remedio3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio3KeyPressed

    private void JTextField_Codigo_Remedio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio4ActionPerformed

    private void JTextField_Codigo_Remedio4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio4KeyPressed

    private void JTextField_Codigo_Remedio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio5ActionPerformed

    private void JTextField_Codigo_Remedio5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio5KeyPressed

    private void JTextField_Codigo_Remedio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio6ActionPerformed

    private void JTextField_Codigo_Remedio6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio6KeyPressed

    private void JTextField_Codigo_Remedio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio7ActionPerformed

    private void JTextField_Codigo_Remedio7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_Codigo_Remedio7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_Codigo_Remedio7KeyPressed

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked

    }//GEN-LAST:event_usersMouseClicked

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
    
    }//GEN-LAST:event_adduserActionPerformed

    private void updateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuserActionPerformed
  
    }//GEN-LAST:event_updateuserActionPerformed

    private void deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserActionPerformed
     
    }//GEN-LAST:event_deleteuserActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosAtt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconX4;
    private javax.swing.JLabel JLabel_Codigo_Remedio;
    private javax.swing.JLabel JLabel_Codigo_Remedio2;
    private javax.swing.JLabel JLabel_Codigo_Remedio3;
    private javax.swing.JLabel JLabel_Codigo_Remedio4;
    private javax.swing.JLabel JLabel_Codigo_Remedio5;
    private javax.swing.JLabel JLabel_Codigo_Remedio6;
    private javax.swing.JLabel JLabel_Codigo_Remedio7;
    private javax.swing.JLabel JLabel_Titulo;
    private javax.swing.JScrollPane JScrollPane_FornecedorEndereco;
    private javax.swing.JSeparator JSeparador;
    private javax.swing.JTextArea JTextArea_FornecedorEndereco;
    private javax.swing.JTextField JTextField_Codigo_Remedio3;
    private javax.swing.JTextField JTextField_Codigo_Remedio4;
    private javax.swing.JTextField JTextField_Codigo_Remedio5;
    private javax.swing.JTextField JTextField_Codigo_Remedio6;
    private javax.swing.JTextField JTextField_Codigo_Remedio7;
    public javax.swing.JButton adduser;
    public javax.swing.JButton deleteuser;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoIFSP_LIFE;
    public javax.swing.JComboBox<String> pro_day;
    public javax.swing.JComboBox<String> pro_month;
    public javax.swing.JComboBox<String> pro_year;
    public javax.swing.JButton updateuser;
    private javax.swing.JTable users;
    // End of variables declaration//GEN-END:variables
}
